server:
    port: 8080

spring:
    cloud:
        gateway:
            server:
                webflux:
                    default-filters: [ ]
                    discovery:
                        locator:
                            enabled: false

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8500/eureka/
    instance:
        prefer-ip-address: true


security:
    jwt:
        secret-key: ${JWT_SECRET}
    cookie:
        name: accessToken