server:
    port: 8100

spring:
    datasource:
        # createDatabaseIfNotExist: MySQL creates the user_service database on the first start
        url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/user_service?createDatabaseIfNotExist=true
        username: ${MYSQL_USERNAME:root}
        password: ${MYSQL_ROOT_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
    kafka:
        producer:
            bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            acks: all
            retries: 3

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8500/eureka/
    instance:
        prefer-ip-address: true

security:
    jwt:
        secret-key: ${JWT_SECRET}
        expiration-time: 3600
        issuer: microurl.ly
    cookie:
        name: accessToken
        expiration-time: 3600
    kafka:
        topic:
            deleted: user.deleted
            admin:
                userState: user.state
